"""QA reason codes -- Spec #001 SS14. Extensible; not exhaustive."""
from __future__ import annotations

from enum import Enum


class ReasonCode(str, Enum):
    MISSING_BAR = "MISSING_BAR"
    DUPLICATE_BAR = "DUPLICATE_BAR"
    ZERO_VOLUME = "ZERO_VOLUME"
    OHLC_INVALID = "OHLC_INVALID"
    NEGATIVE_PRICE = "NEGATIVE_PRICE"
    SUSPICIOUS_GAP = "SUSPICIOUS_GAP"
    STALE_PRICE = "STALE_PRICE"
    CORPORATE_ACTION_UNRESOLVED = "CORPORATE_ACTION_UNRESOLVED"
    ADJUSTMENT_MISMATCH = "ADJUSTMENT_MISMATCH"
    STATUS_CONFLICT = "STATUS_CONFLICT"
    IDENTIFIER_CONFLICT = "IDENTIFIER_CONFLICT"
    INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"
    SOURCE_DISCREPANCY = "SOURCE_DISCREPANCY"


class Severity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
